Repository sb01-monew-team03/sb01-monew-team03, pull requests merged in 2025-04, with the labels that each got.

#9 [ FEATURE ] 댓글 Entity 및 dto 생성
  src/main/java/team03/monew/dto/comments/data/CommentDto.java
  src/main/java/team03/monew/dto/comments/data/CommentLikeDto.java
  src/main/java/team03/monew/dto/comments/request/CommentCreateRequest.java
  src/main/java/team03/monew/dto/comments/request/CommentUpdateRequest.java
  src/main/java/team03/monew/entity/comments/Comment.java
  src/main/java/team03/monew/entity/comments/CommentLike.java
Labels: feature

#7 [ FEATURE ] 관심사 Entitiy 및 DTO 생성
  README.md
  src/main/java/team03/monew/config/JpaConfig.java
  src/main/java/team03/monew/config/gitpush.java
  src/main/java/team03/monew/dto/common/CursorPageResponse.java
  src/main/java/team03/monew/dto/gitpush.java
  src/main/java/team03/monew/dto/interest/InterestDto.java
  src/main/java/team03/monew/dto/interest/InterestRegisterRequest.java
  src/main/java/team03/monew/dto/interest/InterestUpdateRequest.java
  src/main/java/team03/monew/dto/interest/SubscriptionDto.java
  src/main/java/team03/monew/entity/base/BaseEntity.java
  src/main/java/team03/monew/entity/base/BaseUpdatableEntity.java
  src/main/java/team03/monew/entity/gitpush.java
  src/main/java/team03/monew/entity/interest/Interest.java
  src/main/java/team03/monew/entity/interest/Keyword.java
  src/main/java/team03/monew/entity/interest/Subscription.java
  src/main/java/team03/monew/entity/interest/SubscriptionId.java
Labels: feature

#13 [ FEATURE ] USER 서비스 테스트 작성 및 구현
  src/main/java/team03/monew/mapper/user/UserMapper.java
  src/main/java/team03/monew/repository/user/UserRepository.java
  src/main/java/team03/monew/service/AuthService.java
  src/main/java/team03/monew/service/UserService.java
  src/main/java/team03/monew/service/user/AuthService.java
  src/main/java/team03/monew/service/user/UserService.java
  src/main/java/team03/monew/util/exception/gitpush.java
  src/test/java/team03/monew/service/user/AuthServiceTest.java
  src/test/java/team03/monew/service/user/UserServiceTest.java
Labels: feature

#17 [feature] 활동 내역 관리 entity 및 dto 생성
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/team03/monew/dto/activity/ActivityDto.java
  src/main/java/team03/monew/entity/activity/Activity.java
  src/main/java/team03/monew/entity/article/Article.java
  src/main/java/team03/monew/entity/user/User.java
Labels: feature

#20 [chore] Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
Labels: documentation

#26 [ FEATURE ] USER 서비스 및 리포지토리 테스트 구현 및 리팩토링
  build.gradle
  src/main/java/team03/monew/config/JpaConfig.java
  src/main/java/team03/monew/dto/user/UserUpdateRequest.java
  src/main/java/team03/monew/entity/base/BaseDeletableEntity.java
  src/main/java/team03/monew/entity/user/User.java
  src/main/java/team03/monew/mapper/user/UserMapper.java
  src/main/java/team03/monew/service/user/AuthService.java
  src/main/java/team03/monew/service/user/UserService.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/resources/schema.sql
  src/test/java/team03/monew/repository/user/UserRepositoryTest.java
  src/test/java/team03/monew/service/user/UserServiceTest.java
  src/test/resources/application-test.yaml
Labels: feature

#27 [feature] ActivityDto 수정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/team03/monew/dto/activity/ActivityDto.java
Labels: feature

#22 [feature] DB 스키마 추가
  src/main/resources/schema.sql
Labels: feature

#29 [ FEATURE ] Interest 수정, 삭제 기능 추가, QueryDSL 설정 추가
  .github/ISSUE_TEMPLATE/custom.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  checkstyle/intellij-java-google-style.xml
  src/main/java/team03/monew/config/QueryDslConfig.java
  src/main/java/team03/monew/controller/gitpush.java
  src/main/java/team03/monew/dto/interest/InterestFindRequest.java
  src/main/java/team03/monew/entity/base/BaseUpdatableEntity.java
  src/main/java/team03/monew/entity/comments/Comment.java
  src/main/java/team03/monew/entity/comments/CommentLike.java
  src/main/java/team03/monew/entity/interest/Interest.java
  src/main/java/team03/monew/entity/interest/Keyword.java
  src/main/java/team03/monew/entity/interest/Subscription.java
  src/main/java/team03/monew/entity/interest/SubscriptionId.java
  src/main/java/team03/monew/mapper/interest/InterestMapper.java
  src/main/java/team03/monew/repository/interest/CustomInterestRepository.java
  src/main/java/team03/monew/repository/interest/CustomInterestRepositoryImpl.java
  src/main/java/team03/monew/repository/interest/InterestRepository.java
  src/main/java/team03/monew/service/interest/InterestService.java
  src/main/java/team03/monew/service/interest/InterestServiceImpl.java
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/service/interest/InterestServiceTest.java
Labels: feature

#34 [ FEATURE ] 댓글 관리 서비스 구현
  src/main/java/team03/monew/dto/comments/CommentCreateRequest.java
  src/main/java/team03/monew/dto/comments/CommentDto.java
  src/main/java/team03/monew/dto/comments/CommentLikeDto.java
  src/main/java/team03/monew/dto/comments/CommentUpdateRequest.java
  src/main/java/team03/monew/dto/comments/request/CommentCreateRequest.java
  src/main/java/team03/monew/dto/comments/request/CommentUpdateRequest.java
  src/main/java/team03/monew/entity/comments/Comment.java
  src/main/java/team03/monew/entity/comments/CommentLike.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/main/java/team03/monew/repository/comments/CommentRepository.java
  src/main/java/team03/monew/service/comments/CommentService.java
  src/main/java/team03/monew/util/exception/comments/CommentNotFoundException.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
Labels: feature

#35 [ FEATURE ] 관심사 목록 조회 기능 구현
  src/main/java/team03/monew/dto/interest/InterestFindRequest.java
  src/main/java/team03/monew/entity/interest/Interest.java
  src/main/java/team03/monew/repository/interest/CustomInterestRepository.java
  src/main/java/team03/monew/repository/interest/CustomInterestRepositoryImpl.java
  src/main/java/team03/monew/repository/interest/InterestRepository.java
  src/main/java/team03/monew/service/interest/InterestService.java
  src/main/java/team03/monew/service/interest/InterestServiceImpl.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/interest/EmptyKeywordListException.java
  src/main/java/team03/monew/util/exception/interest/InterestAlreadyExistException.java
  src/main/java/team03/monew/util/exception/interest/InterestException.java
  src/main/java/team03/monew/util/exception/interest/InterestNotFoundException.java
  src/main/java/team03/monew/util/exception/interest/OrderByValueException.java
  src/main/resources/schema.sql
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/service/interest/InterestServiceTest.java
Labels: feature

#33 [ FEATURE ] 사용자 컨트롤러 테스트 및 구현
  src/main/java/team03/monew/config/AdminInitializer.java
  src/main/java/team03/monew/controller/user/AuthController.java
  src/main/java/team03/monew/controller/user/UserController.java
  src/main/java/team03/monew/entity/user/User.java
  src/main/java/team03/monew/service/user/AuthService.java
  src/main/java/team03/monew/service/user/UserService.java
  src/main/java/team03/monew/service/user/impl/AuthServiceImpl.java
  src/main/java/team03/monew/service/user/impl/UserServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/team03/monew/controller/user/AuthControllerTest.java
  src/test/java/team03/monew/controller/user/UserControllerTest.java
  src/test/java/team03/monew/repository/user/UserRepositoryTest.java
  src/test/java/team03/monew/service/user/AuthServiceTest.java
  src/test/java/team03/monew/service/user/UserServiceTest.java
Labels: feature

#38 [ REFACTOR ] 사용자 서비스 메서드 추가 및 관련 유틸 수정
  build.gradle
  src/main/java/team03/monew/mapper/user/UserMapper.java
  src/main/java/team03/monew/service/user/UserService.java
  src/main/java/team03/monew/service/user/impl/AuthServiceImpl.java
  src/main/java/team03/monew/service/user/impl/UserServiceImpl.java
Labels: refactor

#42 [ FEATURE ] 댓글 관리 서비스, 서비스 테스트 코드 작성
  src/main/java/team03/monew/dto/comments/CommentDto.java
  src/main/java/team03/monew/dto/comments/CommentLikeDto.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/main/java/team03/monew/repository/comments/CommentLikeRepository.java
  src/main/java/team03/monew/repository/comments/CommentRepository.java
  src/main/java/team03/monew/service/comments/CommentService.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/comments/AlreadyLikedException.java
  src/main/java/team03/monew/util/exception/comments/CommentNotFoundException.java
  src/main/java/team03/monew/util/exception/comments/LikeNotFoundException.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
Labels: feature

#41 [ FEATURE ] Notification Service 및 Repository 구현
  build.gradle
  gradlew
  src/main/java/team03/monew/dto/activity/ActivityDto.java
  src/main/java/team03/monew/entity/notification/Notification.java
  src/main/java/team03/monew/mapper/notification/NotificationMapper.java
  src/main/java/team03/monew/repository/comment/CommentRepository.java
  src/main/java/team03/monew/repository/notification/CumtomNotificationRepositoryImpl.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/repository/notification/NotificationRepository.java
  src/main/java/team03/monew/repository/subscription/SubscriptionRepository.java
  src/main/java/team03/monew/service/notification/NotificationService.java
  src/main/java/team03/monew/service/notification/NotificationServiceImpl.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/comment/CommentException.java
  src/main/java/team03/monew/util/exception/comment/CommentNotFoundException.java
  src/main/java/team03/monew/util/exception/notification/NotificationException.java
  src/main/java/team03/monew/util/exception/notification/NotificationNotFoundException.java
Labels: feature

#46 [ FEATURE ] 관심사 구독자 수 변경 기능 추가
  src/main/java/team03/monew/entity/interest/Interest.java
  src/main/java/team03/monew/service/interest/InterestService.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
  src/main/java/team03/monew/service/interest/impl/SubscriptionServiceImpl.java
  src/test/java/team03/monew/service/interest/SubscriptionServiceTest.java
Labels: feature

#48 [ FEATURE ] 사용자 권한 및 테스트, 프론트 리소스 추가
  src/main/java/team03/monew/config/WebConfig.java
  src/main/java/team03/monew/controller/user/UserController.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/user/ForbiddenException.java
  src/main/java/team03/monew/util/interceptor/UserInterceptor.java
  src/main/resources/static/assets/index-D30UMZL2.css
  src/main/resources/static/assets/index-DF13B-h9.js
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
  src/test/java/team03/monew/controller/user/AuthControllerTest.java
  src/test/java/team03/monew/controller/user/UserControllerTest.java
  src/test/java/team03/monew/integration/user/UserFlowIntegrationTest.java
Labels: feature

#56 [ FEATURE ] 알림 관리 controller 생성
  src/main/java/team03/monew/config/api/NotificationApi.java
  src/main/java/team03/monew/controller/notification/NotificationController.java
  src/main/java/team03/monew/dto/notification/NotificationFindRequest.java
  src/main/java/team03/monew/service/notification/NotificationService.java
  src/main/java/team03/monew/service/notification/NotificationServiceImpl.java
Labels: feature

#51 [ FEATURE ] 사용자 권한 변경 및 서비스 수정, 테스트 수정
  src/main/java/team03/monew/config/WebConfig.java
  src/main/java/team03/monew/controller/user/AuthController.java
  src/main/java/team03/monew/controller/user/UserController.java
  src/main/java/team03/monew/dto/user/UserDto.java
  src/main/java/team03/monew/repository/user/UserRepository.java
  src/main/java/team03/monew/service/user/impl/AuthServiceImpl.java
  src/main/java/team03/monew/service/user/impl/UserServiceImpl.java
  src/main/java/team03/monew/util/exception/user/UserNotFoundException.java
  src/main/java/team03/monew/util/interceptor/UserInterceptor.java
  src/test/java/team03/monew/controller/user/AuthControllerTest.java
  src/test/java/team03/monew/controller/user/UserControllerTest.java
  src/test/java/team03/monew/integration/user/UserFlowIntegrationTest.java
  src/test/java/team03/monew/repository/user/UserRepositoryTest.java
  src/test/java/team03/monew/service/user/AuthServiceTest.java
  src/test/java/team03/monew/service/user/UserServiceTest.java
Labels: feature

#55 [ FEATURE ] 관심사 관리 컨트롤러 구현
  src/main/java/team03/monew/controller/interest/InterestController.java
  src/main/java/team03/monew/controller/interest/SubscriptionController.java
  src/main/java/team03/monew/dto/interest/InterestFindRequest.java
  src/main/java/team03/monew/dto/interest/InterestRegisterRequest.java
  src/main/java/team03/monew/repository/comment/CommentRepository.java
  src/main/java/team03/monew/repository/interest/InterestRepository.java
  src/main/java/team03/monew/repository/interest/SubscriptionRepository.java
  src/main/java/team03/monew/repository/interest/custom/CustomInterestRepository.java
  src/main/java/team03/monew/repository/interest/custom/CustomInterestRepositoryImpl.java
  src/main/java/team03/monew/repository/subscription/SubscriptionRepository.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
  src/main/java/team03/monew/service/notification/NotificationServiceImpl.java
  src/test/java/team03/monew/controller/interest/InterestControllerTest.java
  src/test/java/team03/monew/controller/interest/SubscriptionControllerTest.java
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/service/interest/InterestServiceTest.java
Labels: feature

#57 [ FEATURE ] 댓글 컨트롤러, 테스트 작성
  src/main/java/team03/monew/controller/comments/CommentController.java
  src/main/java/team03/monew/dto/comments/CommentCursorPageResponse.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/test/java/team03/monew/controller/comments/CommentControllerTest.java
Labels: feature

#52 [ FEATURE ] 알림 관리 서비스 및 레포지토리 생성 완료
  build.gradle
  src/main/java/team03/monew/config/QueryDslConfig.java
  src/main/java/team03/monew/entity/article/Article.java
  src/main/java/team03/monew/entity/notification/Notification.java
  src/main/java/team03/monew/repository/article/ArticleRepository.java
  src/main/java/team03/monew/repository/notification/CumtomNotificationRepositoryImpl.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
  src/main/java/team03/monew/service/notification/NotificationService.java
  src/main/java/team03/monew/service/notification/NotificationServiceImpl.java
  src/main/java/team03/monew/util/exception/comment/CommentException.java
  src/main/java/team03/monew/util/exception/comment/CommentNotFoundException.java
  src/main/java/team03/monew/util/exception/notification/NotificationNotFoundException.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
  src/test/java/team03/monew/service/notification/NotificationServiceImplTest.java
Labels: feature

#58 [ FEATURE ] 알림 관리 controller 수정
  src/main/java/team03/monew/config/api/NotificationApi.java
  src/main/java/team03/monew/controller/notification/NotificationController.java
  src/main/java/team03/monew/dto/notification/NotificationFindRequest.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
  src/main/java/team03/monew/service/notification/NotificationServiceImpl.java
  src/test/java/team03/monew/controller/notification/NotificationControllerTest.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
  src/test/java/team03/monew/service/notification/NotificationServiceImplTest.java
Labels: feature

#59 [ TEST ] 알림 관리 repository 테스트 추가
  src/test/java/team03/monew/repository/notification/NotificationRepositoryTest.java
Labels: feature

#63 [ FEATURE ] 관심사 관리 컨트롤러 수정
  src/main/java/team03/monew/controller/interest/InterestController.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/interest/UnauthorizedException.java
  src/main/java/team03/monew/util/interest/AdminValidator.java
  src/test/java/team03/monew/controller/interest/InterestControllerTest.java
  src/test/java/team03/monew/controller/interest/SubscriptionControllerTest.java
Labels: feature

#68 [ REFACTOR ] 관심사 관리 swagger api 추가, Service 리팩토링
  src/main/java/team03/monew/config/api/interest/InterestApi.java
  src/main/java/team03/monew/config/api/interest/SubscriptionApi.java
  src/main/java/team03/monew/controller/interest/InterestController.java
  src/main/java/team03/monew/controller/interest/SubscriptionController.java
  src/main/java/team03/monew/dto/interest/PaginationDto.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
  src/main/java/team03/monew/service/interest/impl/SubscriptionServiceImpl.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/interest/ExcessiveRetryException.java
  src/main/java/team03/monew/util/interest/InterestConstants.java
Labels: refactor

#69 [ FEATURE ] 활동 관리 controller 구현
  src/main/java/team03/monew/controller/activity/Activity.java
  src/main/java/team03/monew/dto/article/ArticleViewDto.java
  src/main/java/team03/monew/dto/comments/CommentActivityDto.java
  src/main/java/team03/monew/dto/comments/CommentLikeActivityDto.java
  src/main/java/team03/monew/dto/user/UserActivityDto.java
  src/main/java/team03/monew/mapper/ArticleViewMapper.java
  src/main/java/team03/monew/mapper/comments/CommentLikeMapper.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/main/java/team03/monew/mapper/interest/SubscriptionMapper.java
  src/main/java/team03/monew/repository/comments/CommentRepository.java
  src/main/java/team03/monew/service/activity/ActivityService.java
  src/main/java/team03/monew/service/activity/ActivityServiceImpl.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
Labels: feature

#67 [ FEATURE ] 뉴스 기사 관리 서비스 구현
  src/main/java/team03/monew/entity/article/Article.java
  src/main/java/team03/monew/mapper/article/ArticleMapper.java
  src/main/java/team03/monew/repository/article/ArticleRepository.java
  src/main/java/team03/monew/service/article/ArticleService.java
  src/main/java/team03/monew/service/article/ArticleServiceImpl.java
  src/main/java/team03/monew/util/exception/ErrorCode.java
  src/main/java/team03/monew/util/exception/article/ArticleException.java
  src/main/java/team03/monew/util/exception/article/ArticleNotFoundException.java
  src/test/java/team03/monew/service/article/ArticleServiceTest.java
  src/test/java/team03/monew/service/notification/NotificationServiceImplTest.java
Labels: feature

#71 [ TEST ] 관심사 관리 테스트 추가
  build.gradle
  src/main/java/team03/monew/repository/interest/custom/CustomInterestRepositoryImpl.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
  src/main/java/team03/monew/util/interest/InterestConstants.java
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/repository/user/UserRepositoryTest.java
  src/test/java/team03/monew/service/interest/InterestServiceTest.java
Labels: test

#72 [ FEATURE ] 댓글 페이지네이션 구현
  src/main/java/team03/monew/controller/comments/CommentController.java
  src/main/java/team03/monew/dto/comments/CommentCursorPageResponse.java
  src/main/java/team03/monew/dto/comments/CommentListRequest.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/main/java/team03/monew/repository/comments/CommentRepository.java
  src/main/java/team03/monew/service/comments/CommentService.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
  src/test/java/team03/monew/controller/comments/CommentControllerTest.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
Labels: feature
