Repository sb01-monew-team03/sb01-monew-team03, pull requests merged in 2025-05, with the labels that each got.

#75 [ FEATURE ] 로그 관리 기능 추가
  build.gradle
  src/main/java/team03/monew/config/MDCLoggingFilter.java
  src/main/java/team03/monew/config/S3Config.java
  src/main/java/team03/monew/config/SchedulingConfig.java
  src/main/java/team03/monew/repository/interest/custom/CustomInterestRepositoryImpl.java
  src/main/java/team03/monew/service/article/ArticleServiceImpl.java
  src/main/java/team03/monew/service/log/S3LogService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/service/article/ArticleServiceTest.java
Labels: feature

#77 [ FIX ] 각종 에러 해결
  src/main/java/team03/monew/controller/activity/ActivityController.java
  src/main/java/team03/monew/mapper/article/ArticleViewMapper.java
  src/main/java/team03/monew/mapper/comments/CommentLikeMapper.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/main/java/team03/monew/repository/comments/CommentRepository.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepositoryImpl.java
  src/main/java/team03/monew/service/activity/ActivityServiceImpl.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
  src/main/java/team03/monew/service/interest/impl/SubscriptionServiceImpl.java
  src/test/java/team03/monew/controller/activity/ActivityControllerTest.java
  src/test/java/team03/monew/repository/notification/NotificationRepositoryTest.java
  src/test/java/team03/monew/service/activity/ActivityServiceTest.java
  src/test/java/team03/monew/service/article/ArticleServiceTest.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
Labels: bug

#81 [ REFACTOR ] 관심사 관리 서비스 수정
  .gitignore
  src/main/java/team03/monew/event/subscription/SubscriptionCreateEvent.java
  src/main/java/team03/monew/event/subscription/SubscriptionDeleteEvent.java
  src/main/java/team03/monew/event/subscription/SubscriptionEventListener.java
  src/main/java/team03/monew/repository/interest/custom/CustomInterestRepositoryImpl.java
  src/main/java/team03/monew/service/interest/InterestReader.java
  src/main/java/team03/monew/service/interest/InterestService.java
  src/main/java/team03/monew/service/interest/impl/InterestReaderImpl.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
  src/main/java/team03/monew/service/interest/impl/SubscriptionServiceImpl.java
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/service/interest/InterestServiceTest.java
  src/test/java/team03/monew/service/interest/SubscriptionServiceTest.java
Labels: refactor

#83 [ REFACTOR ] InterestServiceImpl 리팩토링
  src/main/java/team03/monew/controller/interest/InterestController.java
  src/main/java/team03/monew/dto/interest/PaginationDto.java
  src/main/java/team03/monew/entity/interest/Interest.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/team03/monew/service/interest/OptimisticLockTest.java
Labels: refactor

#84 [ FEATURE ] 알림 삭제 배치 처리
  build.gradle
  src/main/java/team03/monew/config/batch/NotificationDeleteBatchConfig.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/service/notification/scheduler/NotificationScheduler.java
Labels: feature

#86 [ REFACTOR ] 브랜치명 수정
  build.gradle
  src/main/java/team03/monew/config/batch/NotificationDeleteBatchConfig.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/service/notification/scheduler/NotificationScheduler.java
Labels: refactor

#91 [ REFACTOR ] 댓글 서비스, 컨트롤러 테스트 수정
  src/main/java/team03/monew/controller/comments/CommentController.java
  src/main/java/team03/monew/dto/comments/CommentListRequest.java
  src/main/java/team03/monew/mapper/comments/CommentMapper.java
  src/main/java/team03/monew/repository/comments/CommentRepository.java
  src/main/java/team03/monew/service/comments/CommentServiceImpl.java
  src/test/java/team03/monew/controller/comments/CommentControllerTest.java
  src/test/java/team03/monew/service/comments/CommentServiceTest.java
Labels: refactor

#92 [ FEATURE ] spring actuator 추가
  src/main/java/team03/monew/config/batch/NotificationDeleteBatchConfig.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepositoryImpl.java
  src/main/java/team03/monew/service/notification/scheduler/NotificationScheduler.java
Labels: feature

#95 [ FIX ] 관심사 검색 문제 해결
  src/main/java/team03/monew/dto/interest/InterestFindRequest.java
  src/main/java/team03/monew/service/log/S3LogService.java
Labels: bug

#97 [ REFACTOR ] 회원가입 및 닉네임 수정 dto
  src/main/java/team03/monew/dto/user/UserRegisterRequest.java
  src/main/java/team03/monew/dto/user/UserUpdateRequest.java
Labels: refactor

#99 [ FIX ] 알림 관리 관련 버그 수정
  build.gradle
  src/main/java/team03/monew/controller/notification/NotificationController.java
  src/main/java/team03/monew/entity/article/Article.java
  src/main/java/team03/monew/service/article/ArticleServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/schema.sql
Labels: bug

#103 [ FEATURE ] github actions ci 추가
  .github/workflows/ci.yaml
  build.gradle
  src/test/java/team03/monew/integration/user/UserFlowIntegrationTest.java
  src/test/java/team03/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/team03/monew/service/interest/OptimisticLockTest.java
  src/test/resources/application-test.yaml
Labels: feature

#105 [ DOCS ] README.md 수정
  README.md
Labels: documentation

#108 [ FEATURE ] mongo DB 연동
  build.gradle
  src/main/java/team03/monew/config/MongoDBConfig.java
  src/main/java/team03/monew/controller/activity/ActivityController.java
  src/main/java/team03/monew/document/ActivityDocument.java
  src/main/java/team03/monew/dto/user/ActivityDto.java
  src/main/java/team03/monew/mapper/activity/ActivityMapper.java
  src/main/java/team03/monew/repository/activity/ActivityRepository.java
  src/main/java/team03/monew/service/activity/ActivityService.java
  src/main/java/team03/monew/service/activity/ActivityServiceImpl.java
  src/main/java/team03/monew/service/activity/MongoActivityServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/test/java/team03/monew/controller/activity/ActivityControllerTest.java
  src/test/java/team03/monew/service/activity/ActivityServiceTest.java
Labels: feature

#110 [ FEATURE ] Article 컨트롤러 추가 및 기사 수집 기능 추가
  build.gradle
  src/main/java/team03/monew/config/api/ArticleApi.java
  src/main/java/team03/monew/controller/article/ArticleController.java
  src/main/java/team03/monew/dto/article/ArticleCreateRequest.java
  src/main/java/team03/monew/dto/article/ArticleDto.java
  src/main/java/team03/monew/dto/article/ArticleFindRequest.java
  src/main/java/team03/monew/dto/article/ArticleRestoreDto.java
  src/main/java/team03/monew/entity/article/Article.java
  src/main/java/team03/monew/entity/article/ArticleView.java
  src/main/java/team03/monew/mapper/activity/ActivityMapper.java
  src/main/java/team03/monew/mapper/article/ArticleMapper.java
  src/main/java/team03/monew/mapper/article/ArticleViewMapper.java
  src/main/java/team03/monew/repository/article/ArticleRepository.java
  src/main/java/team03/monew/repository/article/ArticleRepositoryCustom.java
  src/main/java/team03/monew/repository/article/ArticleRepositoryImpl.java
  src/main/java/team03/monew/repository/article/ArticleViewRepository.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepositoryImpl.java
  src/main/java/team03/monew/service/activity/ActivityServiceImpl.java
  src/main/java/team03/monew/service/article/ArticleService.java
  src/main/java/team03/monew/service/article/ArticleServiceImpl.java
  src/main/java/team03/monew/service/article/RssFetcherService.java
  src/main/java/team03/monew/service/article/scheduler/ArticleScheduler.java
  src/test/java/team03/monew/service/activity/ActivityServiceTest.java
  src/test/java/team03/monew/service/article/ArticleServiceTest.java
Labels: feature, refactor

#115 [ FIX ] ArticleService 테스트 실패항목 해결
  src/main/java/team03/monew/dto/article/ArticleFindRequest.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepository.java
  src/main/java/team03/monew/repository/notification/CustomNotificationRepositoryImpl.java
  src/main/resources/schema.sql
  src/test/java/team03/monew/service/activity/ActivityServiceTest.java
  src/test/java/team03/monew/service/article/ArticleServiceTest.java
Labels: test

#117 [ FIX ] 트랜잭션 문제로 insert/update/delete 안되는 문제 해결
  src/main/java/team03/monew/config/JpaConfig.java
  src/main/java/team03/monew/config/MongoDBConfig.java
  src/main/resources/application-dev.yaml
Labels: bug

#120 [ DOCS ] README.md 수정
  README.md
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
Labels: documentation

#119 [ fix ] notification controller and service
  src/main/java/team03/monew/config/api/NotificationApi.java
  src/main/java/team03/monew/controller/article/ArticleController.java
  src/main/java/team03/monew/controller/notification/NotificationController.java
  src/main/java/team03/monew/dto/notification/NotificationFindRequest.java
  src/main/java/team03/monew/service/notification/NotificationService.java
  src/main/java/team03/monew/service/notification/NotificationServiceImpl.java
  src/test/java/team03/monew/controller/notification/NotificationControllerTest.java
  src/test/java/team03/monew/service/notification/NotificationServiceImplTest.java
Labels: bug

#122 [ FIX ] articleView 중복 에러 해결
  src/main/java/team03/monew/entity/article/ArticleView.java
Labels: bug

#124 [ FIX ] Article pagination 오류 해결
  src/main/java/team03/monew/dto/article/ArticleFindRequest.java
  src/main/java/team03/monew/entity/article/ArticleView.java
  src/main/java/team03/monew/service/article/ArticleServiceImpl.java
Labels: bug

#126 [ FIX ] 뉴스 기사 관심사 조회 오류해결
  src/main/java/team03/monew/dto/article/ArticleFindRequest.java
  src/main/java/team03/monew/repository/article/ArticleRepositoryImpl.java
  src/main/java/team03/monew/service/article/ArticleServiceImpl.java
  src/main/java/team03/monew/service/article/RssFetcherService.java
Labels: bug

#132 [ FIX ] interest limit 관련 코드 수정
  src/main/java/team03/monew/dto/interest/InterestFindRequest.java
  src/main/java/team03/monew/dto/interest/PaginationDto.java
  src/main/java/team03/monew/service/interest/impl/InterestServiceImpl.java
Labels: bug
